name: manajemen_stok_barang
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.18.0

  intl: ^0.18.0

  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
