// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP_Anzi9rugcsojTBO_5hU2THFhjVzdhE',
    appId: '1:1052423263874:web:7a0b98fae98d15650a069b',
    messagingSenderId: '1052423263874',
    projectId: 'manajemen-stok-barang-82f0b',
    authDomain: 'manajemen-stok-barang-82f0b.firebaseapp.com',
    storageBucket: 'manajemen-stok-barang-82f0b.firebasestorage.app',
    measurementId: 'G-XYQYCRGBDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_jiQItCEGmdPYGDSqvVr30-Gt70qweVY',
    appId: '1:1052423263874:android:2d05766b47e1c6860a069b',
    messagingSenderId: '1052423263874',
    projectId: 'manajemen-stok-barang-82f0b',
    storageBucket: 'manajemen-stok-barang-82f0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZu7butaIW-bZ3HQelbdlsGBt4nhOB3g',
    appId: '1:1052423263874:ios:1160d6f57031cd880a069b',
    messagingSenderId: '1052423263874',
    projectId: 'manajemen-stok-barang-82f0b',
    storageBucket: 'manajemen-stok-barang-82f0b.firebasestorage.app',
    iosBundleId: 'com.example.manajemenStokBarang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZu7butaIW-bZ3HQelbdlsGBt4nhOB3g',
    appId: '1:1052423263874:ios:1160d6f57031cd880a069b',
    messagingSenderId: '1052423263874',
    projectId: 'manajemen-stok-barang-82f0b',
    storageBucket: 'manajemen-stok-barang-82f0b.firebasestorage.app',
    iosBundleId: 'com.example.manajemenStokBarang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP_Anzi9rugcsojTBO_5hU2THFhjVzdhE',
    appId: '1:1052423263874:web:9b21d50dacddbe1b0a069b',
    messagingSenderId: '1052423263874',
    projectId: 'manajemen-stok-barang-82f0b',
    authDomain: 'manajemen-stok-barang-82f0b.firebaseapp.com',
    storageBucket: 'manajemen-stok-barang-82f0b.firebasestorage.app',
    measurementId: 'G-L3C9LR1H5L',
  );
}
